server: 
  port: 9527
 
spring: 
  application: 
    name: microservicecloud-zuul-gateway
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance: 
    instance-id: gateway-9527.com
    prefer-ip-address: true 

zuul: 
  prefix: /luojia  #所有访问都需要加一个访问前缀（即加在端口后面 http://myzuul.com:9527/luojia/mydept/dept/get/2）
#  ignored-services: microservicecloud-dept  #忽略真实的访问地址（即真实的访问地址不允许被访问）
  ignored-services: "*"  #忽略所有的真实的访问地址（即真实的访问地址不允许被访问）
  routes: 
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**  #使用 mydept 来替换掉原来真实的访问地址


info:
  app.name: luojia-microcloud
  company.name: www.atguigu.com
  build.artifactId: microservicecloud-zuul-gateway-9527
  build.version: 0.0.1-SNAPSHOT