server: 
  port: 8001 #服务端口

spring: 
  application: 
    name: cloud-payment-service #服务名
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver #数据库驱动包
    url: jdbc:mysql://localhost:3306/springcloud?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root

eureka:
  client:
    #表示是否将自己注册进eurekaServer，默认为true
    register-with-eureka: true
    #是否从EurekaServer 抓取已有的注册中心，默认为true，单节点无所谓，集群必须设置true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      # 集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
#  instance:
#    instance-id: payment8001
#    # 访问路径可以显示ip地址
#    prefer-ip-address: true
  devtools: 
    restart: 
      enabled: true #是否支持热部署

mybatis: 
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.luojia.springcloud.entities  #所有entity别名所在包